[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = "qemu-system-aarch64 -M virt,secure=on,virtualization=on -cpu cortex-a53 -smp 1 -m size=4G -nographic -serial mon:stdio -S -s -kernel"
