[package]
name = "arm64"
version = "0.1.0"
edition = "2024"

[features]
cortex-a53 = []

[dependencies]
entry-macro = { path = "macros/entry", features = ["arm64"] }
cfg-asm = { path = "../macros/cfg-asm" }

arbitrary-int = "=2.2.0"
bitbybit = { version = "=2.0.0", features = ["introspect"] }
derive-mmio = "=0.8.0"
safe-mmio = "=0.3.1"

pastey = "=0.2.3"
